[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200

; Cấu hình đúng cho N16R8: 16MB Flash + 8MB OPI PSRAM
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi     ; Flash QIO + PSRAM OPI
board_build.partitions = partitions_n16r8.csv

; Ép PlatformIO tìm code ở thư mục src thay vì main (theo cấu trúc gốc của pico-fido)
board_build.cmake_extra_args =
    -D ESP_PLATFORM=1